### ISSUE TITLE
How do I use PageLinks for requests?

### ISSUE THREAD

**Issue by f-squirrel** [aurora-rs/stellar-horizon-rs#7]
I am trying to download operations for a ledger as follows:

```rust
         let request = api::operations::for_ledger(block_id.as_i64() as i32)
            .with_include_failed(true)
            .with_join(stellar_horizon::api::Join::Transactions)
            .with_order(&stellar_horizon::request::Order::Ascending);

        let (_, operations_page) = client.request(request).await.unwrap();

        println!("operation link: {:#?}", operations_page.links);
        println!("count: {}", operations_page.records.len());
```

It returns `10` operations. The block contains more than 900 transactions.
How do I tell the client to continue requesting starting from the "next" page link?
I tried to convert it somehow to request but did not manage.

I can extract the "cursor" value from the href as `str`, but it seems a bit overkill.

Thank you!

**Comment by bjorn** [comment]
> How do I tell the client to continue requesting starting from the "next" page link?

Normally you can obtain the cursor from an operation using `operation.base().paging_token`. In my code I have something like this:
```rust
let mut cursor = String::new();
loop {
    let request = api::operations::for_account(&account)
        .with_limit(PAGE_LIMIT)
        .with_cursor(&cursor);
    let (_, response) = client.request(request).await?;
    let records_len = response.records.len();

    cursor = response.records.last().map(|operation| operation.base().paging_token.clone()).unwrap_or_default();

    // ...

    if records_len < PAGE_LIMIT as usize {
        break;
    }
}

**Comment by f-squirrel** [comment]
> ```rust
> (|operation| operation.base().paging_token.clone()).unwrap_or_default();
> ```

Hey, thank you for the reply.
At the moment, I have switched to requesting payments.
The problem there is that in need to do `match` on every payment to extract the exact type of operation and get its `base`.

**Comment by bjorn** [comment]
> At the moment, I have switched to requesting payments.
> The problem here is that I need to do `match` on every payment to extract the exact type of operation and get its `base`.

Hmm, yes, it would be nice to provide a similar function to `Operation::base()` for the `Payment` enum. Maybe you'd like to do another pull request? Something like:
```rust
impl Payment {
    pub fn base(&self) -> &OperationBase {
        match self {
```


> Do I understand correctly that `paging_token` is the cursor?

Yes, see the docs at https://developers.stellar.org/api/horizon/introduction/pagination/page-arguments, in which the URL includes a `cursor={paging_token}` parameter and https://developers.stellar.org/api/horizon/resources/operations/object/, documents the `paging_token` as "A cursor value for use in [pagination](https://developers.stellar.org/api/horizon/introduction/pagination/).".

**Comment by f-squirrel** [comment]
> > At the moment, I have switched to requesting payments.
> > The problem here is that I need to do `match` on every payment to extract the exact type of operation and get its `base`.
> 
> Hmm, yes, it would be nice to provide a similar function to `Operation::base()` for the `Payment` enum. Maybe you'd like to do another pull request? Something like:
> 
> ```rust
> impl Payment {
>     pub fn base(&self) -> &OperationBase {
>         match self {
> ```
> 
> > Do I understand correctly that `paging_token` is the cursor?
> 
> Yes, see the docs at https://developers.stellar.org/api/horizon/introduction/pagination/page-arguments, in which the URL includes a `cursor={paging_token}` parameter and https://developers.stellar.org/api/horizon/resources/operations/object/, documents the `paging_token` as "A cursor value for use in [pagination](https://developers.stellar.org/api/horizon/introduction/pagination/).".

Please find here: https://github.com/aurora-rs/stellar-horizon-rs/pull/10.

**Comment by bjorn** [comment]
> Please find here: #10.

Thanks! I think we can close this issue now. :-)
